# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish artifacts to Github Packages

on:
  release:
    types: [ created ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'

    - name: Run tests
      run: sbt test

    - name: Publish artifacts
      run: sbt publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
